# Github action building the project with different versions of Java and uploading the test coverage to Coveralls.

name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  STOREPASS: password

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 21 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up dependencies
        run: sudo apt-get install -y ykcs11 opensc-pkcs11

      - name: Compile
        run: |
          mvn -version
          mvn -B clean compile

      - name: Packaging
        run: mvn -B package -DskipTests

      - name: Archive artifacts
        if: ${{ matrix.java == '8' }}
        uses: actions/upload-artifact@v4
        with:
          name: jsign-artifacts
          path: |
            jsign/target/jsign-*.jar
            !jsign/target/jsign-*-javadoc.jar
            !jsign/target/jsign-*-sources.jar
            !jsign/target/jsign-*_proguard_base.jar
            jsign/target/*.deb
            jsign/target/*.rpm
            jsign-core/target/jsign-core-*.jar
            !jsign-core/target/jsign-core-*-javadoc.jar
            !jsign-core/target/jsign-core-*-sources.jar
            !jsign-core/target/jsign-core-*-tests.jar
